const tickets = [
  {
    category: "Q1 2022",
    color: "red",
    title: "NFT Safety 101 Video",
    owner: "Vinayaka Iyer",
    avatar: "https://snipboard.io/9w1iyQ.jpg",
    status: "done",
    priority: 5,
    progress: 40,
    description:
      "Make a video showcasing how to work with NFTs safely, including how to know if one is not genuine",
    timestamp: "2022-03-11T07:36:17+0000",
  },
  {
    category: "Q2 2022",
    color: "red",
    title: "Build and sell AI Model",
    owner: "Vinayaka Iyer",
    avatar: "https://snipboard.io/9w1iyQ.jpg",
    status: "working on it",
    priority: 2,
    progress: 70,
    description: "make a video about AI",
    timestamp: "2022-03-11T07:36:17+0000",
  },
  {
    category: "Q2 2022",
    color: "blue",
    title: "Build bot",
    owner: "Vinayaka Iyer",
    avatar: "https://snipboard.io/9w1iyQ.jpg",
    status: "working on it",
    priority: 3,
    progress: 10,
    description: "make a video about working on a bot",
    timestamp: "2022-03-11T07:36:17+0000",
  },
];
